language: python

matrix:
  include:
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

    - os: linux
      language: python
      python: "3.7"


install:
  - pip install -r requirements.txt

script:
  - python train.py
  - python example_prediction.py

after_success:
  - echo "Successfull."
