language: python

#matrix:
#  include:
##    - os: windows
##      language: sh
##      python: "3.8"
##      before_install:
##        - choco install python --version 3.8.0
##        - python -m pip install --upgrade pip
##        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
#    - os: osx
#      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
#      language: shell       # 'language: python' is an error on Travis CI macOS
#
#    - os: linux
#      language: python
#      python: "3.7"
#
#
#install:
#  - pip install -r requirements.txt

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode13.1  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install -r requirements.txt
# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only

script:
  - python3 train.py || python train.py
  - python3 example_prediction.py || python example_prediction.py

after_success:
  - echo "Successfull."
