language: python

matrix:
  include:
    - os: windows
      language: sh
      python: "3.8"
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

    - os: linux
      language: python
      python: "3.8"


install:
  - pip install -r requirements.txt

script:
  - python train.py
  - python example_prediction.py

after_success:
  - echo "Successfull."
