language: python

python:
  - "3.6"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - python train.py
  - python example_prediction.py

after_success:
  - echo "Successfull."
